### ISSUE TITLE
Flow diagram

### ISSUE THREAD

**Issue by ZoologyDave** [ZoologyDave/WildlifeTradeNutrition#3]
@BollieHooth happy to lead on this?

**Comment by BollieHooth** [comment]
I'm a bit confused. Do you mean Fig 1? I've had a first go, though will may need some tweaks (please take a look and comment @ZoologyDave @hommedesmuffins).
![Screen Shot 2020-05-29 at 12 18 53](https://user-images.githubusercontent.com/65966773/83254910-61c2fb00-a1a7-11ea-8a81-3e82d35aff57.png)

**Comment by ZoologyDave** [comment]
Yes! This was really just to organise thoughts. That looks ace!

**Comment by ZoologyDave** [comment]
Where did you get the little images, by the way? This looks pro!

**Comment by BollieHooth** [comment]
😎

I just got them off the internet! Noun project, icon finder etc. I often get comments for my ‘professional looking’ figures, and asked which software I use… I literally make them all in PowerPoint 😅
